### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by matysek** [xolox/python-verboselogs#1]
When trying to install verboselogs, it fails with this message:

```
pip install verboselogs
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting verboselogs
  Using cached verboselogs-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-jvyp5scv\verboselogs\setup.py", line 9, in <module>
        readme_text = open(readme_file, 'r').read()
      File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2011: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-jvyp5scv\verboselogs
```

**Comment by xolox** [comment]
Hi Martin and thanks for the feedback! I just released version 1.0.2 which should (to the best of my knowledge) fix this issue. If the problem persists then feel free to re-open this issue.
