### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by aress31** [xolox/python-verboselogs#14]
Hi @xolox,

I am a huge fan of `coloredlogs`, I consistently use it in all my `Python` projects and by reading the doc I have just came across `verboselogs`. Obviously, I now need to adopt it as well, however, I am currently having a tough time getting `verboselogs` to work - at the `root logger level`.

Please see my code and kindly advise where I messed up:

```python
import coloredlogs
import logging
import verboselogs


def init_logger(log_level):
    verboselogs.install()
    coloredlogs.install(
        fmt="%(level_name)s %(message)s",
        level=logging.getLevelName(log_level)
    )

    logging.getLogger('requests').setLevel(logging. ERROR)
    logging.getLogger('urllib3').setLevel(logging. ERROR)
```

```python
import logging
import verboselogs

from configuration.Logger import init_logger

def main():
    args = init_args()
    init_logger(args.log_level)
    print(logging.getLogger(__name__))
    # <VerboseLogger __main__ (SPAM)>
    logging.spam('This is a trace message')

if __name__ == "__main__":
    main()
```

The resulting `error stack-trace`:

```python
Traceback (most recent call last):
  File "C:\Users\REDACTED.py", line 95, in <module>
    main()
  File "C:\Users\REDACTED.py", line 27, in main
    logging. Spam('This is a trace message')
AttributeError: module 'logging' has no attribute 'spam'
```

**Comment by Cheekie25** [comment]
I think you need to first create a logger like in the exemple : 
```logger = logging.getLogger(__name__) # will be a VerboseLogger instance```

And log with that instead of using logging directly.

**Comment by marcelzwiers** [comment]
In case this may help anyone, in my usecase, subclassing `logging.Logger` and then using `setLoggerClass()` (as done by verboselogs) did not work robustly (messages of imported plugins were ignored). Instead, I only got it all to work by extending the current logger (i.e. by using `getLoggerClass()`):

```python
    # Register custom log levels + methods
    logging.SUCCESS = 25
    logging.addLevelName(logging.SUCCESS, 'SUCCESS')
    def success(self, message, *args, **kws):
        if self.isEnabledFor(logging.SUCCESS): 
           self._log(logging.SUCCESS, message, args, **kws)
    logging.getLoggerClass().success = success
```
etc
